### ISSUE TITLE
Main page background

### ISSUE THREAD

**Issue by e-roy** [e-roy/glitch#17]
[Reference](https://github.com/e-roy/glitch/pull/15#issue-1159026386)

@myaowy Looks like it's a radial type gradient

[Tailwind Gradient](https://tailwindcss.com/docs/gradient-color-stops)

[A fun tool](https://cssgradient.io/)

[Github discussion how to add custom](https://github.com/tailwindlabs/tailwindcss/discussions/2599)
[Reference to discussion](https://play.tailwindcss.com/fBVvvF0Phn)

**Comment by meowyx** [comment]
@e-roy  okay then, I will take a look at it and will try to figure out. Thank you.
